#!/bin/bash
USAGE="Usage: $0 IP1 IP2 IP3 ..."

if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

# Store the data here for persistence
DATA_DIR="/home/student/yaman/a2group99/cassandra/data"

MASTER="$1"
while (( "$#" )); do
    if [ "$1" = "$MASTER" ]; 
    then
        COMMAND="docker run --name cassandra-node -d \
                 -e CASSANDRA_BROADCAST_ADDRESS=$1 \
                 -p 7000:7000 -p 9042:9042 \
                 -v $DATA_DIR:/var/lib/cassandra \
                 cassandra"
    else
        COMMAND="docker run --name cassandra-node -d \
                 -e CASSANDRA_BROADCAST_ADDRESS=$1 \
                 -p 7000:7000 -p 9042:9042 \
                 -e CASSANDRA_SEEDS=$MASTER \
                 -v $DATA_DIR:/var/lib/cassandra \
                 cassandra"
    fi

	ssh student@$1 "docker container stop cassandra-node; docker container rm cassandra-node; $COMMAND;"
	
	while true;
	do
		sleep 5
		STATUS=$(docker exec -it cassandra-node nodetool status | grep -e $1)
		STATUSUN=$(echo $STATUS | grep -e "UN")
		echo $STATUS
		[[ ! -z "$STATUSUN" ]] && break;
	done;
	shift
done

